packages:
  - packages/cache
  - packages/codegen-api
  - packages/codegen-sql
  - packages/codegen-ts
  - packages/config
  - packages/feature-gates
  - packages/grammar-extension-api
  - packages/id
  - packages/model
  - packages/model-persisted
  - packages/schema
  - packages/schema-api
  - packages/sql
  - packages/util
  - packages/value
  - packages/zone
