packages:
  - build-all
  - packages/cache
  - packages/codegen-api
  - packages/codegen-sql
  - packages/codegen-ts
  - packages/config
  - packages/feature-gates
  - packages/grammar-extension-api
  - packages/id
  - packages/instrument
  - packages/migration
  - packages/model
  - packages/model-persisted
  - packages/query
  - packages/react
  - packages/runtime
  - packages/schema
  - packages/schema-api
  - packages/sql
  - packages/util
  - packages/value
  - packages/zone
  - connectors/absurd-sql-connector
  - connectors/capacitor-sqlite-connector
  - connectors/sqlite3-connector
  - connectors/sqljs-connector
  - connectors/wa-sqlite-connector
